#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

# Init submodules
git submodule update --init --recursive

# Stow all files in directories
stow -S $(ls -d */)

# Install vim plugins
vim +PluginInstall +qall
# Install Go Binaries for vim
vim +GoInstallBinaries
