#!/bin/sh

# Remove existing polybar/sxhkd processes
killall polybar
killall sxhkd

# Load color scheme from wal
wal -R -q

# Fix monitor order
bspc monitor primary --swap ^1

# Set up bspwm desktops and polybars for each monitor
MONITOR=$(xrandr --query | grep " connected primary" | cut -d " " -f 1)
env MONITOR=$MONITOR
bspc monitor $MONITOR -d I II III IV V VI VII

for MONITOR in $(xrandr --query | grep " connected [^primary]" | cut -d " " -f 1)
do
	env MONITOR=$MONITOR
	bspc monitor $MONITOR -d VIII IX X
done

# key daemon
sxhkd &

# source colors
. "${HOME}/.cache/wal/colors.sh"

# bspc config
bspc config active_border_color "$background_transparent"
bspc config top_padding 				 20
bspc config border_width         0
bspc config window_gap					 16
bspc config border_width				 2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus			 true
